package gowrap

import (
	"fmt"
	"strings"
)

// GenerateMaggieStubs generates Maggie class definitions for a PackageModel.
// Returns a map of filename → content. Package-level functions go in "stubs.mag"
// (namespace "Go", class e.g. "Strings"). Struct types go in "stubs_types.mag"
// (namespace e.g. "Go::Strings") so that a struct like Builder registers as
// "Go::Strings::Builder" in Globals, matching the FQN used by gen_go.go.
func GenerateMaggieStubs(model *PackageModel) (map[string]string, error) {
	namespace := GoPackageToMaggieNamespace(model.ImportPath)
	// e.g., "Go::Strings" → parent namespace "Go", class name "Strings"
	parts := strings.SplitN(namespace, "::", 2)
	parentNS := parts[0]
	pkgClass := parts[1] // e.g., "Strings", "Json"

	result := make(map[string]string)

	// --- stubs.mag: package namespace class with class methods (functions) ---
	var b strings.Builder
	fmt.Fprintf(&b, "\" Code generated by mag wrap %s. DO NOT EDIT.\n", model.ImportPath)
	fmt.Fprintf(&b, "namespace: '%s'\n\n", parentNS)

	if len(model.Functions) > 0 || len(model.Constants) > 0 {
		fmt.Fprintf(&b, "%s subclass: Object\n", pkgClass)

		for _, fn := range model.Functions {
			selector := GoNameToMaggieSelector(fn.Name, paramNames(fn.Params))
			fmt.Fprintf(&b, "  classMethod: %s [ <primitive> ]\n", formatSelector(selector, fn.Params))
		}

		fmt.Fprintf(&b, "\n")
	}
	result["stubs.mag"] = b.String()

	// --- stubs_types.mag: struct types under full namespace ---
	// Under namespace "Go::Strings", class "Builder" registers as
	// "Go::Strings::Builder", matching GoNameToMaggieClassName in gen_go.go.
	var hasStructs bool
	for _, tp := range model.Types {
		if tp.IsStruct {
			hasStructs = true
			break
		}
	}

	if hasStructs {
		var tb strings.Builder
		fmt.Fprintf(&tb, "\" Code generated by mag wrap %s. DO NOT EDIT.\n", model.ImportPath)
		fmt.Fprintf(&tb, "namespace: '%s'\n\n", namespace)

		for _, tp := range model.Types {
			if !tp.IsStruct {
				continue
			}
			fmt.Fprintf(&tb, "%s subclass: Object\n", tp.Name)

			for _, m := range tp.Methods {
				selector := GoNameToMaggieSelector(m.Name, paramNames(m.Params))
				fmt.Fprintf(&tb, "  method: %s [ <primitive> ]\n", formatSelector(selector, m.Params))
			}

			fmt.Fprintf(&tb, "\n")
		}
		result["stubs_types.mag"] = tb.String()
	}

	return result, nil
}

// formatSelector creates the method signature for the Maggie stub.
// e.g., selector "contains:substr:" with 2 params → "contains: s substr: t"
func formatSelector(selector string, params []ParamModel) string {
	if len(params) == 0 {
		return selector
	}

	parts := strings.Split(selector, ":")
	// Remove trailing empty string from split
	for len(parts) > 0 && parts[len(parts)-1] == "" {
		parts = parts[:len(parts)-1]
	}

	var b strings.Builder
	for i, part := range parts {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(part)
		b.WriteString(": ")
		if i < len(params) {
			b.WriteString(paramVarName(params[i], i))
		} else {
			fmt.Fprintf(&b, "p%d", i)
		}
	}
	return b.String()
}

func paramVarName(p ParamModel, idx int) string {
	if p.Name != "" && p.Name != "_" {
		return lcFirst(p.Name)
	}
	return fmt.Sprintf("p%d", idx)
}
