package gowrap

import (
	"fmt"
	"go/types"
	"strings"
)

// GenerateGoGlue generates the Go wrapper code for a PackageModel.
// The output is a Go source file that registers primitives with the VM.
func GenerateGoGlue(model *PackageModel) (string, error) {
	namespace := GoPackageToMaggieNamespace(model.ImportPath)
	pkgPath := model.ImportPath

	var b strings.Builder

	// Header
	fmt.Fprintf(&b, "// Code generated by mag wrap %s. DO NOT EDIT.\n", model.ImportPath)
	fmt.Fprintf(&b, "package wrap_%s\n\n", sanitizePackageName(model.Name))
	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t\"reflect\"\n")
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "\tpkg %q\n", model.ImportPath)
	fmt.Fprintf(&b, "\t\"github.com/chazu/maggie/vm\"\n")
	fmt.Fprintf(&b, ")\n\n")

	// Suppress unused import warnings
	fmt.Fprintf(&b, "var _ = reflect.TypeOf\n")
	fmt.Fprintf(&b, "\n")

	// RegisterPrimitives function
	fmt.Fprintf(&b, "// RegisterPrimitives registers all wrapped Go types and functions with the VM.\n")
	fmt.Fprintf(&b, "func RegisterPrimitives(v *vm.VM) {\n")

	// Register types
	for _, tp := range model.Types {
		if !tp.IsStruct {
			continue
		}
		className := GoNameToMaggieClassName(namespace, tp.Name)
		fmt.Fprintf(&b, "\t// Type: %s\n", tp.Name)
		if len(tp.Methods) > 0 {
			fmt.Fprintf(&b, "\t%sClass := v.RegisterGoType(%q, reflect.TypeOf((*pkg.%s)(nil)))\n",
				lcFirst(tp.Name), className, tp.Name)
		} else {
			fmt.Fprintf(&b, "\tv.RegisterGoType(%q, reflect.TypeOf((*pkg.%s)(nil)))\n",
				className, tp.Name)
		}
	}

	if len(model.Types) > 0 {
		fmt.Fprintf(&b, "\n")
	}

	// Package-level namespace class for class methods (functions)
	if len(model.Functions) > 0 || len(model.Constants) > 0 {
		fmt.Fprintf(&b, "\t// Package namespace class for class-level methods\n")
		fmt.Fprintf(&b, "\tnsClass := v.RegisterGoType(%q, reflect.TypeOf((*struct{})(nil)))\n", namespace)
		fmt.Fprintf(&b, "\t_ = nsClass\n\n")
	}

	// Register package-level functions as class methods on namespace class
	for _, fn := range model.Functions {
		generateFunctionBinding(&b, fn, pkgPath)
	}

	// Register methods on types
	for _, tp := range model.Types {
		if !tp.IsStruct {
			continue
		}
		for _, m := range tp.Methods {
			generateMethodBinding(&b, m, tp, pkgPath)
		}
	}

	fmt.Fprintf(&b, "}\n")

	return b.String(), nil
}

// hasUnconvertibleParam returns true if any param has a type that goTypeConversion
// cannot handle (returns empty string). Such methods must be skipped since they'd
// produce uncompilable code.
func hasUnconvertibleParam(params []ParamModel, pkgPath string) (bool, string) {
	for _, p := range params {
		conv := goTypeConversion(p.GoType, "x", pkgPath)
		if conv == "" {
			return true, p.TypeStr
		}
	}
	return false, ""
}

// paramNames extracts the Name field from each ParamModel.
func paramNames(params []ParamModel) []string {
	names := make([]string, len(params))
	for i, p := range params {
		names[i] = p.Name
	}
	return names
}

func generateFunctionBinding(b *strings.Builder, fn FunctionModel, pkgPath string) {
	selector := GoNameToMaggieSelector(fn.Name, paramNames(fn.Params))
	if bad, typStr := hasUnconvertibleParam(fn.Params, pkgPath); bad {
		fmt.Fprintf(b, "\t// Skipped: %s (unconvertible parameter type: %s)\n", fn.Name, typStr)
		return
	}

	fmt.Fprintf(b, "\tnsClass.AddClassMethod(v.Selectors, %q, vm.NewPrimitiveMethod(%q, func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {\n",
		selector, selector)

	// Generate body into temp buffer to check if v is used
	var body strings.Builder
	for i, p := range fn.Params {
		conv := goTypeConversion(p.GoType, fmt.Sprintf("args[%d]", i), pkgPath)
		if conv != "" {
			fmt.Fprintf(&body, "\t\targ%d := %s\n", i, conv)
		}
	}
	callArgs := buildCallArgs(fn.Params, pkgPath)
	callExpr := fmt.Sprintf("pkg.%s(%s)", fn.Name, strings.Join(callArgs, ", "))
	writeReturnHandling(&body, callExpr, fn.Results, fn.ReturnsErr)

	bodyStr := body.String()
	if strings.Contains(bodyStr, "v.") {
		fmt.Fprintf(b, "\t\tv := vmPtr.(*vm.VM)\n")
	} else {
		fmt.Fprintf(b, "\t\t_ = vmPtr\n")
	}
	b.WriteString(bodyStr)

	fmt.Fprintf(b, "\t}))\n\n")
}

func generateMethodBinding(b *strings.Builder, m FunctionModel, tp TypeModel, pkgPath string) {
	selector := GoNameToMaggieSelector(m.Name, paramNames(m.Params))
	if bad, typStr := hasUnconvertibleParam(m.Params, pkgPath); bad {
		fmt.Fprintf(b, "\t// Skipped: %s.%s (unconvertible parameter type: %s)\n", tp.Name, m.Name, typStr)
		return
	}

	varName := lcFirst(tp.Name) + "Class"
	fmt.Fprintf(b, "\t%s.AddPrimitiveMethod(v.Selectors, %q, func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {\n",
		varName, selector)
	fmt.Fprintf(b, "\t\tv := vmPtr.(*vm.VM)\n")

	// Extract Go receiver
	fmt.Fprintf(b, "\t\tgoVal, ok := v.GetGoObject(receiver)\n")
	fmt.Fprintf(b, "\t\tif !ok {\n")
	fmt.Fprintf(b, "\t\t\treturn vm.Nil\n")
	fmt.Fprintf(b, "\t\t}\n")
	fmt.Fprintf(b, "\t\tself := goVal.(*pkg.%s)\n", tp.Name)

	// Extract Go args
	for i, p := range m.Params {
		conv := goTypeConversion(p.GoType, fmt.Sprintf("args[%d]", i), pkgPath)
		if conv != "" {
			fmt.Fprintf(b, "\t\targ%d := %s\n", i, conv)
		}
	}

	callArgs := buildCallArgs(m.Params, pkgPath)
	callExpr := fmt.Sprintf("self.%s(%s)", m.Name, strings.Join(callArgs, ", "))

	writeReturnHandling(b, callExpr, m.Results, m.ReturnsErr)
	fmt.Fprintf(b, "\t})\n\n")
}

func buildCallArgs(params []ParamModel, pkgPath string) []string {
	args := make([]string, len(params))
	for i, p := range params {
		conv := goTypeConversion(p.GoType, fmt.Sprintf("args[%d]", i), pkgPath)
		if conv != "" {
			args[i] = fmt.Sprintf("arg%d", i)
		} else {
			args[i] = fmt.Sprintf("v.ValueToGo(args[%d])", i)
		}
	}
	return args
}

func writeReturnHandling(b *strings.Builder, callExpr string, results []ParamModel, returnsErr bool) {
	if len(results) == 0 {
		fmt.Fprintf(b, "\t\t%s\n", callExpr)
		fmt.Fprintf(b, "\t\treturn vm.Nil\n")
	} else if returnsErr && len(results) == 2 {
		fmt.Fprintf(b, "\t\tresult, err := %s\n", callExpr)
		fmt.Fprintf(b, "\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\treturn v.NewFailureResult(err.Error())\n")
		fmt.Fprintf(b, "\t\t}\n")
		fmt.Fprintf(b, "\t\treturn v.NewSuccessResult(v.GoToValue(result))\n")
	} else if returnsErr && len(results) == 1 {
		fmt.Fprintf(b, "\t\terr := %s\n", callExpr)
		fmt.Fprintf(b, "\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\treturn v.NewFailureResult(err.Error())\n")
		fmt.Fprintf(b, "\t\t}\n")
		fmt.Fprintf(b, "\t\treturn v.NewSuccessResult(vm.Nil)\n")
	} else if len(results) == 1 {
		fmt.Fprintf(b, "\t\tresult := %s\n", callExpr)
		fmt.Fprintf(b, "\t\treturn v.GoToValue(result)\n")
	} else {
		// Multiple non-error results
		resultVars := make([]string, len(results))
		for i := range results {
			resultVars[i] = fmt.Sprintf("r%d", i)
		}
		fmt.Fprintf(b, "\t\t%s := %s\n", strings.Join(resultVars, ", "), callExpr)
		fmt.Fprintf(b, "\t\tarr := make([]vm.Value, %d)\n", len(results))
		for i := range results {
			fmt.Fprintf(b, "\t\tarr[%d] = v.GoToValue(r%d)\n", i, i)
		}
		fmt.Fprintf(b, "\t\treturn v.NewArrayWithElements(arr)\n")
	}
}

// goTypeConversion returns a Go expression that converts a Maggie Value to the
// expected Go type. wrappedPkgPath is the import path of the package being wrapped,
// used to distinguish same-package types (accessed as pkg.X) from external types.
// Returns "" if no direct conversion is available.
func goTypeConversion(t types.Type, valueExpr, wrappedPkgPath string) string {
	// Handle pointer types first.
	if ptr, ok := t.(*types.Pointer); ok {
		elem := ptr.Elem()
		// Pointer to named type (e.g., *TuplePattern): extract via ValueToGo type assertion.
		if named, isNamed := elem.(*types.Named); isNamed {
			if named.Obj().Pkg() != nil && named.Obj().Pkg().Path() == wrappedPkgPath {
				return fmt.Sprintf("v.ValueToGo(%s).(*pkg.%s)", valueExpr, named.Obj().Name())
			}
			// Pointer to type from another package — unconvertible.
			return ""
		}
		// Pointer to basic type (e.g., *string, *int64): convert value, take address.
		if basic, ok := elem.Underlying().(*types.Basic); ok {
			switch {
			case basic.Info()&types.IsString != 0:
				return fmt.Sprintf("func() *string { s := v.ValueToGo(%s).(string); return &s }()", valueExpr)
			case basic.Info()&types.IsInteger != 0:
				return fmt.Sprintf("func() *%s { n := %s(%s.SmallInt()); return &n }()", basic.Name(), basic.Name(), valueExpr)
			case basic.Info()&types.IsFloat != 0:
				return fmt.Sprintf("func() *%s { f := %s(%s.Float64()); return &f }()", basic.Name(), basic.Name(), valueExpr)
			case basic.Info()&types.IsBoolean != 0:
				return fmt.Sprintf("func() *bool { b := v.ValueToGo(%s).(bool); return &b }()", valueExpr)
			}
		}
		// Unknown pointer target: unconvertible.
		return ""
	}

	// Handle named types.
	if named, ok := t.(*types.Named); ok {
		// Named struct types (value params, not pointers).
		if _, isStruct := named.Underlying().(*types.Struct); isStruct {
			if named.Obj().Pkg() != nil && named.Obj().Pkg().Path() == wrappedPkgPath {
				// GoObject stores *T, dereference to get T value.
				return fmt.Sprintf("*v.ValueToGo(%s).(*pkg.%s)", valueExpr, named.Obj().Name())
			}
			// Struct from another package — unconvertible.
			return ""
		}
		// Named types with basic underlying types (e.g., type Format string).
		// Only handle types from the wrapped package (accessible as pkg.TypeName).
		if basic, ok := named.Underlying().(*types.Basic); ok {
			if named.Obj().Pkg() != nil && named.Obj().Pkg().Path() == wrappedPkgPath {
				castExpr := fmt.Sprintf("pkg.%s", named.Obj().Name())
				switch {
				case basic.Info()&types.IsString != 0:
					return fmt.Sprintf("%s(v.ValueToGo(%s).(string))", castExpr, valueExpr)
				case basic.Info()&types.IsInteger != 0:
					return fmt.Sprintf("%s(%s.SmallInt())", castExpr, valueExpr)
				case basic.Info()&types.IsFloat != 0:
					return fmt.Sprintf("%s(%s.Float64())", castExpr, valueExpr)
				case basic.Info()&types.IsBoolean != 0:
					return fmt.Sprintf("%s(v.ValueToGo(%s).(bool))", castExpr, valueExpr)
				}
			}
			// Named type from another package (e.g., time.Duration) — unconvertible
			// since we can't import the package in the generated code.
			return ""
		}
	}

	underlying := t.Underlying()
	switch u := underlying.(type) {
	case *types.Basic:
		switch {
		case u.Info()&types.IsString != 0:
			return fmt.Sprintf("v.ValueToGo(%s).(string)", valueExpr)
		case u.Info()&types.IsBoolean != 0:
			return fmt.Sprintf("v.ValueToGo(%s).(bool)", valueExpr)
		case u.Info()&types.IsInteger != 0:
			return fmt.Sprintf("%s(%s.SmallInt())", u.Name(), valueExpr)
		case u.Info()&types.IsFloat != 0:
			return fmt.Sprintf("%s(%s.Float64())", u.Name(), valueExpr)
		}
	case *types.Slice:
		if basic, ok := u.Elem().(*types.Basic); ok && basic.Kind() == types.Byte {
			return fmt.Sprintf("[]byte(v.ValueToGo(%s).(string))", valueExpr)
		}
	case *types.Interface:
		// Only handle empty interface (interface{} / any). Non-empty interfaces
		// like context.Context can't be auto-converted from Maggie values.
		if u.NumMethods() == 0 {
			return fmt.Sprintf("v.ValueToGo(%s)", valueExpr)
		}
	}
	return ""
}

func sanitizePackageName(name string) string {
	return strings.ReplaceAll(name, "-", "_")
}

func lcFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
