package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/chazu/maggie/compiler"
)

// primDocEntry holds a primitive method docstring keyed by class and selector.
type primDocEntry struct {
	ClassName string
	Selector  string
	ClassSide bool
	DocString string
}

// generatePrimDocstrings scans all .mag files for <primitive> stubs with
// docstrings and writes a Go source file that applies them at runtime.
func generatePrimDocstrings(files []string, outputPath string) error {
	var entries []primDocEntry

	for _, path := range files {
		content, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		sf, err := compiler.ParseSourceFileFromString(string(content))
		if err != nil {
			continue
		}
		for _, classDef := range sf.Classes {
			for _, md := range classDef.Methods {
				if md.IsPrimitiveStub && md.DocString != "" {
					entries = append(entries, primDocEntry{
						ClassName: classDef.Name,
						Selector:  md.Selector,
						ClassSide: false,
						DocString: md.DocString,
					})
				}
			}
			for _, md := range classDef.ClassMethods {
				if md.IsPrimitiveStub && md.DocString != "" {
					entries = append(entries, primDocEntry{
						ClassName: classDef.Name,
						Selector:  md.Selector,
						ClassSide: true,
						DocString: md.DocString,
					})
				}
			}
		}
	}

	if len(entries) == 0 {
		return nil
	}

	// Sort for deterministic output
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].ClassName != entries[j].ClassName {
			return entries[i].ClassName < entries[j].ClassName
		}
		if entries[i].ClassSide != entries[j].ClassSide {
			return !entries[i].ClassSide
		}
		return entries[i].Selector < entries[j].Selector
	})

	var b strings.Builder
	b.WriteString("// Code generated by cmd/bootstrap; DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import \"github.com/chazu/maggie/vm\"\n\n")
	b.WriteString("// applyPrimitiveDocstrings copies docstrings from .mag source\n")
	b.WriteString("// <primitive> stubs onto Go-registered primitive methods.\n")
	b.WriteString("// Primitive methods are not persisted in the image format,\n")
	b.WriteString("// so this is the only way to make their docstrings available\n")
	b.WriteString("// at runtime (e.g., via mag help).\n")
	b.WriteString("func applyPrimitiveDocstrings(vmInst *vm.VM) {\n")

	for _, e := range entries {
		b.WriteString(fmt.Sprintf("\tsetPrimDoc(vmInst, %q, %q, %v, %q)\n",
			e.ClassName, e.Selector, e.ClassSide, e.DocString))
	}

	b.WriteString("}\n\n")
	b.WriteString("func setPrimDoc(vmInst *vm.VM, className, selector string, classSide bool, doc string) {\n")
	b.WriteString("\tcls := vmInst.Classes.Lookup(className)\n")
	b.WriteString("\tif cls == nil {\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	b.WriteString("\tselID := vmInst.Selectors.Lookup(selector)\n")
	b.WriteString("\tif selID < 0 {\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvt := cls.VTable\n")
	b.WriteString("\tif classSide {\n")
	b.WriteString("\t\tvt = cls.ClassVTable\n")
	b.WriteString("\t}\n")
	b.WriteString("\tm := vt.Lookup(selID)\n")
	b.WriteString("\tif m == nil {\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif ds, ok := m.(vm.DocStringable); ok && ds.DocString() == \"\" {\n")
	b.WriteString("\t\tds.SetDocString(doc)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return os.WriteFile(outputPath, []byte(b.String()), 0644)
}
