package main

import (
	"os"
	"path/filepath"
	"testing"
)

// ---------------------------------------------------------------------------
// detectMaggieDir
// ---------------------------------------------------------------------------

func TestBuild_DetectMaggieDir_ReturnsNonEmpty(t *testing.T) {
	dir := detectMaggieDir()
	if dir == "" {
		t.Fatal("detectMaggieDir returned empty string")
	}
	// When running from the repo, it should point to the repo root
	// which contains go.mod.
	goMod := filepath.Join(dir, "go.mod")
	if _, err := os.Stat(goMod); err != nil {
		t.Errorf("expected go.mod at %s, got error: %v", goMod, err)
	}
}

func TestBuild_DetectMaggieDir_FallsBackToEnv(t *testing.T) {
	// When MAGGIE_DIR is set, it should be used as a fallback.
	// We can't easily force runtime.Caller to fail, but we can verify
	// the env var path exists in the function and that the primary
	// path (runtime.Caller) takes precedence.
	orig := os.Getenv("MAGGIE_DIR")
	defer os.Setenv("MAGGIE_DIR", orig)

	os.Setenv("MAGGIE_DIR", "/tmp/fake-maggie")
	dir := detectMaggieDir()
	// runtime.Caller succeeds in tests, so env var should NOT be used
	if dir == "/tmp/fake-maggie" {
		t.Error("expected runtime.Caller path to take precedence over MAGGIE_DIR")
	}
}

// ---------------------------------------------------------------------------
// mapWrapDirsToImports
// ---------------------------------------------------------------------------

func TestBuild_MapWrapDirsToImports_EmptyDir(t *testing.T) {
	dir := t.TempDir()
	result := mapWrapDirsToImports(dir)
	if len(result) != 0 {
		t.Errorf("expected empty map for empty dir, got %v", result)
	}
}

func TestBuild_MapWrapDirsToImports_NonexistentDir(t *testing.T) {
	result := mapWrapDirsToImports("/nonexistent/path/that/does/not/exist")
	if len(result) != 0 {
		t.Errorf("expected empty map for nonexistent dir, got %v", result)
	}
}

func TestBuild_MapWrapDirsToImports_SkipsFiles(t *testing.T) {
	dir := t.TempDir()
	// Create a regular file (not a directory) — should be skipped
	os.WriteFile(filepath.Join(dir, "not-a-dir.go"), []byte("package foo"), 0o644)

	result := mapWrapDirsToImports(dir)
	if len(result) != 0 {
		t.Errorf("expected empty map when only files present, got %v", result)
	}
}

func TestBuild_MapWrapDirsToImports_SubdirWithoutWrapGo(t *testing.T) {
	dir := t.TempDir()
	os.MkdirAll(filepath.Join(dir, "mypkg"), 0o755)
	// No wrap.go inside — should be skipped

	result := mapWrapDirsToImports(dir)
	if len(result) != 0 {
		t.Errorf("expected empty map for subdir without wrap.go, got %v", result)
	}
}

func TestBuild_MapWrapDirsToImports_ValidWrapGo(t *testing.T) {
	dir := t.TempDir()

	// Create a subdirectory with a valid wrap.go
	subdir := filepath.Join(dir, "http")
	os.MkdirAll(subdir, 0o755)
	wrapContent := "// Code generated by mag wrap net/http. DO NOT EDIT.\npackage wrap_http\n"
	os.WriteFile(filepath.Join(subdir, "wrap.go"), []byte(wrapContent), 0o644)

	result := mapWrapDirsToImports(dir)

	if len(result) != 1 {
		t.Fatalf("expected 1 entry, got %d: %v", len(result), result)
	}
	gotDir, ok := result["net/http"]
	if !ok {
		t.Fatalf("expected key 'net/http', got keys: %v", result)
	}
	if gotDir != subdir {
		t.Errorf("expected dir %s, got %s", subdir, gotDir)
	}
}

func TestBuild_MapWrapDirsToImports_MultiplePackages(t *testing.T) {
	dir := t.TempDir()

	packages := []struct {
		subdir     string
		importPath string
	}{
		{"http", "net/http"},
		{"json", "encoding/json"},
		{"fmt", "fmt"},
	}

	for _, pkg := range packages {
		subdir := filepath.Join(dir, pkg.subdir)
		os.MkdirAll(subdir, 0o755)
		content := "// Code generated by mag wrap " + pkg.importPath + ". DO NOT EDIT.\npackage wrap_" + pkg.subdir + "\n"
		os.WriteFile(filepath.Join(subdir, "wrap.go"), []byte(content), 0o644)
	}

	result := mapWrapDirsToImports(dir)

	if len(result) != 3 {
		t.Fatalf("expected 3 entries, got %d: %v", len(result), result)
	}
	for _, pkg := range packages {
		gotDir, ok := result[pkg.importPath]
		if !ok {
			t.Errorf("missing key %q", pkg.importPath)
			continue
		}
		expected := filepath.Join(dir, pkg.subdir)
		if gotDir != expected {
			t.Errorf("for %q: expected dir %s, got %s", pkg.importPath, expected, gotDir)
		}
	}
}

func TestBuild_MapWrapDirsToImports_MalformedHeader(t *testing.T) {
	dir := t.TempDir()

	subdir := filepath.Join(dir, "bad")
	os.MkdirAll(subdir, 0o755)
	// wrap.go without the expected header comment
	os.WriteFile(filepath.Join(subdir, "wrap.go"), []byte("package wrap_bad\n"), 0o644)

	result := mapWrapDirsToImports(dir)
	if len(result) != 0 {
		t.Errorf("expected empty map for malformed header, got %v", result)
	}
}
