// Code generated by cmd/bootstrap; DO NOT EDIT.

package main

import "github.com/chazu/maggie/vm"

// applyPrimitiveDocstrings copies docstrings from .mag source
// <primitive> stubs onto Go-registered primitive methods.
// Primitive methods are not persisted in the image format,
// so this is the only way to make their docstrings available
// at runtime (e.g., via mag help).
func applyPrimitiveDocstrings(vmInst *vm.VM) {
	setPrimDoc(vmInst, "DateTime", "addDays:", false, "Return a new DateTime offset by the given number of days.")
	setPrimDoc(vmInst, "DateTime", "addHours:", false, "Return a new DateTime offset by the given number of hours.")
	setPrimDoc(vmInst, "DateTime", "addMinutes:", false, "Return a new DateTime offset by the given number of minutes.")
	setPrimDoc(vmInst, "DateTime", "addSeconds:", false, "Return a new DateTime offset by the given number of seconds.")
	setPrimDoc(vmInst, "DateTime", "day", false, "Return the day of month (1-31).")
	setPrimDoc(vmInst, "DateTime", "differenceFrom:", false, "Return the difference in seconds between self and another DateTime\n(self - other). Positive if self is later.")
	setPrimDoc(vmInst, "DateTime", "epochMillis", false, "Return the Unix epoch timestamp in milliseconds.")
	setPrimDoc(vmInst, "DateTime", "epochSeconds", false, "Return the Unix epoch timestamp in seconds.")
	setPrimDoc(vmInst, "DateTime", "format:", false, "Format the receiver using a Go layout string.")
	setPrimDoc(vmInst, "DateTime", "hour", false, "Return the hour (0-23).")
	setPrimDoc(vmInst, "DateTime", "minute", false, "Return the minute (0-59).")
	setPrimDoc(vmInst, "DateTime", "month", false, "Return the month (1-12).")
	setPrimDoc(vmInst, "DateTime", "printString", false, "Return an ISO 8601 (RFC3339) string representation.")
	setPrimDoc(vmInst, "DateTime", "second", false, "Return the second (0-59).")
	setPrimDoc(vmInst, "DateTime", "year", false, "Return the year component.")
	setPrimDoc(vmInst, "Float", "acos", false, "Return the arc cosine of the receiver. Result in radians.")
	setPrimDoc(vmInst, "Float", "asin", false, "Return the arc sine of the receiver. Result in radians.")
	setPrimDoc(vmInst, "Float", "atan", false, "Return the arc tangent of the receiver. Result in radians.")
	setPrimDoc(vmInst, "Float", "atan2:", false, "Return the arc tangent of y/x (receiver is y, argument is x),\nusing the signs of both to determine the quadrant. Result in radians.")
	setPrimDoc(vmInst, "Float", "cos", false, "Return the cosine of the receiver (in radians).")
	setPrimDoc(vmInst, "Float", "exp", false, "Return e raised to the power of the receiver.")
	setPrimDoc(vmInst, "Float", "ln", false, "Return the natural logarithm (base e) of the receiver.")
	setPrimDoc(vmInst, "Float", "log10", false, "Return the base-10 logarithm of the receiver.")
	setPrimDoc(vmInst, "Float", "log:", false, "Return the logarithm of the receiver in the given base.")
	setPrimDoc(vmInst, "Float", "pow:", false, "Return the receiver raised to the given power.")
	setPrimDoc(vmInst, "Float", "sin", false, "Return the sine of the receiver (in radians).")
	setPrimDoc(vmInst, "Float", "tan", false, "Return the tangent of the receiver (in radians).")
	setPrimDoc(vmInst, "HttpClient", "delete:", false, "Perform an HTTP DELETE request. Returns the response body as a string,\nor nil on error.\n\n```example\n| result <String> |\nresult := HttpClient new delete: 'http://example.com/api/item/1'\n```")
	setPrimDoc(vmInst, "HttpClient", "get:", false, "Perform an HTTP GET request. Returns the response body as a string,\nor nil on error.\n\n```example\n| body <String> |\nbody := HttpClient new get: 'http://example.com/'\n```")
	setPrimDoc(vmInst, "HttpClient", "post:body:", false, "Perform an HTTP POST request with the given body string.\nUses 'application/octet-stream' as the default content type.\nReturns the response body as a string, or nil on error.\n\n```example\n| result <String> |\nresult := HttpClient new post: 'http://example.com/api' body: 'hello'\n```")
	setPrimDoc(vmInst, "HttpClient", "post:body:contentType:", false, "Perform an HTTP POST request with the given body and content type.\nReturns the response body as a string, or nil on error.\n\n```example\n| result <String> |\nresult := HttpClient new\n    post: 'http://example.com/api'\n    body: '{\"key\": \"value\"}'\n    contentType: 'application/json'\n```")
	setPrimDoc(vmInst, "HttpClient", "put:body:", false, "Perform an HTTP PUT request with the given body string.\nUses 'application/octet-stream' as the content type.\nReturns the response body as a string, or nil on error.\n\n```example\n| result <String> |\nresult := HttpClient new put: 'http://example.com/api/item' body: 'data'\n```")
	setPrimDoc(vmInst, "HttpClient", "new", true, "Create a new HttpClient with a default 30-second timeout.\n\n```example\n| client <HttpClient> |\nclient := HttpClient new\n```")
	setPrimDoc(vmInst, "HttpRequest", "body", false, "Return the request body as a string. The body is read lazily on\nfirst access and cached for subsequent calls.\n\n```example\n| body <String> |\nbody := request body\n```")
	setPrimDoc(vmInst, "HttpRequest", "header:", false, "Return the value of the named HTTP header, or an empty string\nif the header is not present.\n\n```example\n| contentType <String> |\ncontentType := request header: 'Content-Type'\n```")
	setPrimDoc(vmInst, "HttpRequest", "method", false, "Return the HTTP method of the request (e.g. 'GET', 'POST').\n\n```example\nrequest method   \"=> 'GET'\"\n```")
	setPrimDoc(vmInst, "HttpRequest", "path", false, "Return the URL path of the request (e.g. '/api/data').\n\n```example\nrequest path   \"=> '/api/data'\"\n```")
	setPrimDoc(vmInst, "HttpRequest", "queryParam:", false, "Return the value of the named URL query parameter, or an empty\nstring if the parameter is not present.\n\n```example\n\"For URL '/search?q=hello'\"\nrequest queryParam: 'q'   \"=> 'hello'\"\n```")
	setPrimDoc(vmInst, "HttpResponse", "body", false, "Return the body string of this response.\n\n```example\n(HttpResponse new: 200 body: 'hello') body   \"=> 'hello'\"\n```")
	setPrimDoc(vmInst, "HttpResponse", "contentType:", false, "Set the Content-Type header. Convenience method equivalent to\n`self header: 'Content-Type' value: mime`. Returns self for chaining.\n\n```example\nresponse contentType: 'application/json'\n```")
	setPrimDoc(vmInst, "HttpResponse", "header:value:", false, "Set a response header. Returns self for chaining.\n\n```example\nresponse header: 'X-Custom' value: 'my-value'\n```")
	setPrimDoc(vmInst, "HttpResponse", "status", false, "Return the status code of this response.\n\n```example\n(HttpResponse new: 200 body: 'OK') status   \"=> 200\"\n```")
	setPrimDoc(vmInst, "HttpResponse", "new:body:", true, "Create a new HTTP response with the given status code and body string.\n\n```example\nHttpResponse new: 200 body: 'OK'\nHttpResponse new: 404 body: 'Not Found'\nHttpResponse new: 500 body: 'Internal Server Error'\n```")
	setPrimDoc(vmInst, "HttpServer", "isRunning", false, "Return true if the server is currently running.\n\n```example\n| server <HttpServer> |\nserver := HttpServer new: 8080.\nserver isRunning   \"=> false\"\n```")
	setPrimDoc(vmInst, "HttpServer", "port", false, "Return the port number this server is configured to listen on.\n\n```example\n(HttpServer new: 8080) port   \"=> 8080\"\n```")
	setPrimDoc(vmInst, "HttpServer", "route:method:handler:", false, "Register a route handler. The handler block receives an HttpRequest\nand should return an HttpResponse or a string. If method is empty,\nall HTTP methods are accepted. Returns self for chaining.\n\n```example\nserver route: '/api/data' method: 'GET' handler: [:req |\n    HttpResponse new: 200 body: 'OK'\n]\n```")
	setPrimDoc(vmInst, "HttpServer", "serveStatic:from:", false, "Register a static file handler. Requests matching urlPath will be\nserved from dirPath on the filesystem. Returns self for chaining.\n\n```example\nserver serveStatic: '/static/' from: './public'\n```")
	setPrimDoc(vmInst, "HttpServer", "start", false, "Start the server. This blocks the current process until the server\nis stopped. Returns self on clean shutdown, or nil on error.\n\n```example\n| server <HttpServer> |\nserver := HttpServer new: 8080.\n[server start] fork.\n\"Server is now running in background\"\n```")
	setPrimDoc(vmInst, "HttpServer", "stop", false, "Stop the server gracefully with a 5-second shutdown timeout.\nReturns self.\n\n```example\nserver stop\n```")
	setPrimDoc(vmInst, "HttpServer", "new:", true, "Create a new HTTP server listening on the given port.\nThe server is not started until `start` is called.\n\n```example\n| server <HttpServer> |\nserver := HttpServer new: 8080\n```")
	setPrimDoc(vmInst, "Regex", "findAllIn:", false, "Find all matches of this pattern in the given string.\nReturns an Array of matched substrings.")
	setPrimDoc(vmInst, "Regex", "findIn:", false, "Find the first match of this pattern in the given string.\nReturns the matched substring, or nil if no match.")
	setPrimDoc(vmInst, "Regex", "matches:", false, "Test whether the given string matches this pattern.")
	setPrimDoc(vmInst, "Regex", "pattern", false, "Return the original pattern string used to compile this Regex.")
	setPrimDoc(vmInst, "Regex", "printString", false, "Return a human-readable representation.")
	setPrimDoc(vmInst, "Regex", "replaceIn:with:", false, "Replace all occurrences of this pattern in the string with replacement.")
	setPrimDoc(vmInst, "Regex", "split:", false, "Split the string by this pattern. Returns an Array of substrings.")
	setPrimDoc(vmInst, "Regex", "compile:", true, "Compile a regex pattern string. Returns Success wrapping a Regex\non success, or Failure with an error message on invalid pattern.")
}

func setPrimDoc(vmInst *vm.VM, className, selector string, classSide bool, doc string) {
	cls := vmInst.Classes.Lookup(className)
	if cls == nil {
		return
	}
	selID := vmInst.Selectors.Lookup(selector)
	if selID < 0 {
		return
	}
	vt := cls.VTable
	if classSide {
		vt = cls.ClassVTable
	}
	m := vt.Lookup(selID)
	if m == nil {
		return
	}
	if ds, ok := m.(vm.DocStringable); ok && ds.DocString() == "" {
		ds.SetDocString(doc)
	}
}
